spring:
  datasource:
    username: root
    #password: 123456
    #url: jdbc:mysql://192.168.25.131:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: 123456
    url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver