spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage.width: 80
  thumbImage.height: 80
  trackerList: 192.168.25.133:22122
  #trackerList: 122.152.205.72:88

logging:
  level:
    com.usher.mapper: debug